spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=postgres
bot.name=RecommendationRulesBot
bot.token=8667271844:AAGiyLU2b8rFNgwp10OhfQBB7K_V6n2iXJg