spring.application.name=TeamWorkBankAppliaction
spring.datasource.url=jdbc:postgresql://localhost:5432/bankApp
spring.datasource.username=postgres
spring.datasource.password=postgres

spring.jpa.hibernate.ddl-auto=update




