spring.application.name=TeamWorkBankAppliaction
spring.datasource.primary.url=jdbc:postgresql://localhost:5432/bankApp
spring.datasource.primary.username=postgres
spring.datasource.primary.password=postgres

spring.jpa.hibernate.ddl-auto=update